[package]
name = "hasm"
version = "0.1.0"
authors = ["fix-fix <fix-fix@users.noreply.github.com>"]
edition = "2021"
workspace = "../.."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
